### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by DanTheMan827** [tsvcathed/nginx_lancache#3]
It'd be nice if you made a dockerfile for this and configured dockerhub to automatically build with the nginx base image and push when you commit to master

**Comment by jordandalley** [comment]
For sure man. Packaging it up has been on my todo list for a while, but I've mostly just used Github as a way of tracking changes rather than a full blown build. There's a lot of people out there using these caches other than myself now, so there's certainly merit here.

It's not something I've done before, so I'll need to do a bit of research. If you're offering to help though, feel free to dig in :)

**Comment by DanTheMan827** [comment]
assuming you just copy etc from the repo into the host, the Dockerfile would be something like this
```
FROM nginx
COPY etc/ /etc/
EXPOSE 80/tcp
EXPOSE 443/tcp```
I haven't tested that personally though, just from memory.

**Comment by jordandalley** [comment]
Thanks mate. Not sure here. There are a bunch of variables that need inserting into the config depending on the environment it's running in that might make it a bit more complicated
